url: "asherz.ling"
# baseurl: /asherz720.github.io
# Basic Information 
title: Anshun Asher Zheng
# subtitle:
position: M.Sc. Student
# subposition: Chair of the Chinese Student and Scholar Association (CSSA)
# subposition_link: https://nyu-medicine-cssa.github.io
affiliation: University of Edinburgh
subaffiliation: School of Philosophy, Psychology & Language Sciences
affiliation_link: https://www.ed.ac.uk/
subaffiliation_link: https://www.ed.ac.uk/ppls
email: serendipity7@hanyang.ac.kr
address: 3 Charles St, Edinburgh EH8 9AD
address_link: https://www.google.com/maps/place/The+University+of+Edinburgh:+School+of+Philosophy,+Psychology+and+Language+Sciences/@55.94515,-3.1904349,17z/data=!3m2!4b1!5s0x4887c78380a9954d:0x6f0e11144cdbe50c!4m6!3m5!1s0x4887c78486685a27:0xec9d97d8ac15b301!8m2!3d55.94515!4d-3.18786!16s%2Fm%2F0dsb9pw?entry=ttu



# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: minimal light
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/

# Links 
# If you don't need one of them, you may delete the corresponding line.
# google_scholar: https://scholar.google.com/citations?user=bePCCD8AAAAJ&hl=en
cv_link: assets/files/Anshun Zheng.pdf
github_link: https://github.com/asherz720
linkedin: https://www.linkedin.com/in/anshun-zheng-56924020b/
twitter: https://twitter.com/Asher_Zheng00

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
# logo: ./assets/img/logo.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
